name: "Test and Build"
on:
  # FIXME only run on main (i.e. deploy after merge)
  pull_request:
  push:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: jayayeseekay
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: see things
        run: |
          whoami
          ls -lah /etc/docker/daemon.json
          cat /etc/docker/daemon.json
          systemctl status docker

      - name: change things
        run: |
          echo "about to modify docker config"
          echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job", "max-concurrent-uploads": 20 }' > /etc/docker/daemon.json
          systemctl restart docker
          cat /etc/docker/daemon.json
          systemctl status docker
