name: "Test and Build"
on:
  # FIXME only run on main (i.e. deploy after merge)
  pull_request:
  push:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: jayayeseekay
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: run tests
        run: nix develop --command just test
      - name: check formatting
        run: nix develop --command just check-formatting

      - name: build image
        run: nix develop --command just build-image
      - name: push image
        run: nix develop --command just tag-and-push-image
