name: "Test and Build"
on:
  # FIXME only run on main (i.e. deploy after merge)
  pull_request:
  push:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: jayayeseekay
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: just test
      - run: just check-formatting

      - run: just build-image
      - run: docker push --all-tags jayayeseekay/mcchatbot
